Repository vaadin/spring, pull requests merged in 2021-11, with the labels that each got.

#929 chore: update testbench version
  vaadin-spring-tests/pom.xml
Labels: target/18.0

#934 chore: bump version to 20.0
  README.md
  pom.xml
  vaadin-spring-tests/dummy-module/pom.xml
  vaadin-spring-tests/pom.xml
  vaadin-spring-tests/test-mvc-without-endpoints/pom.xml
  vaadin-spring-tests/test-spring-boot-contextpath/pom.xml
  vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
  vaadin-spring-tests/test-spring-boot-scan/pom.xml
  vaadin-spring-tests/test-spring-boot/pom.xml
  vaadin-spring-tests/test-spring-common/pom.xml
  vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  vaadin-spring-tests/test-spring-security-flow/pom.xml
  vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
  vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
  vaadin-spring-tests/test-spring-security-fusion/pom.xml
  vaadin-spring-tests/test-spring-war/pom.xml
  vaadin-spring-tests/test-spring-white-list/pom.xml
  vaadin-spring-tests/test-ts-services-custom-client/pom.xml
  vaadin-spring-tests/test-ts-services/pom.xml
  vaadin-spring/pom.xml
Labels: fusion

#931 feat(stateless): expose VaadinStatelessSecurityConfigurer
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepository.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/SerializedJwtSplitCookieRepository.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepositoryTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/SerializedJwtSplitCookieRepositoryTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/TestSecurityContextHolderStrategy.java
Labels: fusion

#942 Revert "Fix tests"
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCacheTest.java
Labels: target/19.0

#944 fix: Spring Boot 2.6 compatibility
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
Labels: target/19.0

#947 fix: add help for slow scanning
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: target/12.4, target/19.0

#948 fix: Spring Boot 2.6 compatibility (#944) (CP: 12.4)
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
Labels: cherry-pick
