Repository vaadin/spring, pull requests merged in 2021-05, with the labels that each got.

#792 chore: Update lock files for LitElement 2.5
  vaadin-spring-tests/test-spring-security-fusion/package.json
  vaadin-spring-tests/test-spring-security-fusion/pnpm-lock.yaml
Labels: target/17.0

#817 refactor: decouple Spring add-on and DevModeHandler
  vaadin-spring-tests/test-mvc-without-endpoints/pom.xml
  vaadin-spring-tests/test-spring-boot-contextpath/pom.xml
  vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
  vaadin-spring-tests/test-spring-boot-scan/pom.xml
  vaadin-spring-tests/test-spring-boot/pom.xml
  vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  vaadin-spring-tests/test-spring-security-flow/pom.xml
  vaadin-spring-tests/test-spring-security-fusion/pom.xml
  vaadin-spring-tests/test-spring-war/pom.xml
  vaadin-spring-tests/test-spring-white-list/pom.xml
  vaadin-spring-tests/test-ts-services-custom-client/pom.xml
  vaadin-spring-tests/test-ts-services/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
Labels: fusion

#815 fix: annotate default error handler
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/router/SpringRouteNotFoundError.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
Labels: target/12.4, target/16.0, target/17.0

#830 fix: check DevModeHandler presence after production mode
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: fusion
