Repository vaadin/spring, pull requests merged in 2021-12, with the labels that each got.

#951 Add whitelisted-packages' docs URL to logs
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: target/12.4, target/19.0

#961 fix: Fix static resources loading for Spring Boot 2.6, again
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
Labels: target/18.0, target/12.4

#962 test: Test for static resource loading
  vaadin-spring-tests/test-spring-common/src/main/resources/META-INF/resources/metainfresources-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/public/public-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/resources/resources-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/static/static-file.txt
  vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ResourcesIT.java
Labels: target/18.0, target/12.4

#970 test: Test for static resource loading (#962)
  vaadin-spring-tests/test-spring-common/src/main/resources/META-INF/resources/metainfresources-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/public/public-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/resources/resources-file.txt
  vaadin-spring-tests/test-spring-common/src/main/resources/static/static-file.txt
  vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ResourcesIT.java
Labels: cherry-pick

#969 fix: Fix static resources loading for Spring Boot 2.6, again (#961)
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
Labels: cherry-pick

#971 Delete log4j exception
  vaadin-spring-tests/test-spring-war/pom.xml
Labels: target/18.0, target/12.4, target/19.0

#976 test: do not use getInShadowRoot
  vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ParentTemplateIT.java
Labels: target/18.0, target/19.0

#979 test: Make test compatible with Spring boot 2.6
  vaadin-spring-tests/test-spring-security-fusion/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
Labels: target/12.4, target/19.0

#983 test: Enable vaadin-spring test
  vaadin-spring-tests/pom.xml
  vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ResourcesIT.java
  vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/SpringBootOnly.java
  vaadin-spring-tests/test-spring/pom.xml
  vaadin-spring-tests/test-ts-services/pom.xml
Labels: target/12.4, target/19.0
